// A plain static single-page app (copied from grand-slam-gm/vite.config.ts without its front-door
// plugin): file-based routes generated by the router plugin (it must run before the React plugin),
// React, Tailwind, the "@" alias, and a dist/ folder that Cloudflare Pages serves as-is.
import { defineConfig } from "vite";
import { tanstackRouter } from "@tanstack/router-plugin/vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import path from "node:path";

const root = import.meta.dirname;

export default defineConfig({
  plugins: [tanstackRouter({ target: "react", autoCodeSplitting: true }), react(), tailwindcss()],
  resolve: {
    alias: { "@": path.resolve(root, "src") },
    dedupe: ["react", "react-dom", "@tanstack/react-router"],
  },
  build: { outDir: "dist" },
});
